#Don't change this
[config]
  schemaVersion="0.0.1"

[package]
  #Edit these in Directory.Build.props instead, the workflow will automate copying
  #it here for you
  description="A compilation of utils specific to Lethal Company"
  websiteUrl="https://github.com/DecibillyJoel/LCUtils"

  #Change this to true if your mod has any NSFW content. Please follow the rules
  #on image and text content on your listing or your package may be removed
  containsNsfwContent=false

  #This is where you put in dependencies in the format
  #DependencyNamespace-ModName = "version.number.here"
  [package.dependencies]
    BepInEx-BepInExPack="5.4.2100"

#These settings will import the repo's README.md file and the icon in the
#same folder as this TOML file as your icon. Please replace the icon with
#something prettier! You do not need to modify these settings!
[build]
  icon  ="./../../docs/icon.png"
  outdir="./../../artifacts/tspublish/build"
  readme="./../../docs/README.md"

  [[build.copy]]
    source="./../../artifacts/tspublish/dist"
    target="./"

#Don't change this
[general]
  repository="https://thunderstore.io"

#Don't change this
[publish]
  communities=["lethal-company"]
  repository ="https://thunderstore.io"

  #There is a list of tags in the tutorial
  [publish.categories]
    lethal-company=["mods"]
